/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pro1041.ui;

/**
 *
 * @author LaptopAZ.vn
 */
public class UserManualFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserManualFrame
     */
    public UserManualFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setClosable(true);
        setMaximizable(true);
        setTitle("ShoeStoreSys - Hướng Dẫn Sử Dụng");
        setPreferredSize(new java.awt.Dimension(692, 573));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("HƯỚNG DẪN SỬ DỤNG");

        jScrollPane2.setHorizontalScrollBar(null);

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextPane1.setText("Quản lý sản phẩm:\n - Thêm sản phẩm:\n    + Nhập thông tin sản phẩm\n    + Chọn \"Lưu loại giày\"\n    + Chọn \"Thêm sản phẩm\"\n - Cập nhật thông tin sản phẩm:\n    + Click đúp sản phẩm muốn cập nhật trong danh sách sản phẩm\n    + Cập nhật thông tin của sản phẩm\n    + Chọn \"Lưu loại giày\"\n    + Chọn \"Cập nhật\"\n - Tìm kiếm sản phẩm:\n    + Chọn thông tin hoặc nhập từ khóa mã hoặc tên sản phẩm cần tìm\n    + Chọn \"Tìm kiếm\"\nQuản lý nhân viên: (Chỉ có thể truy cập với tài khoản chức vụ Quản lý)\n - Thêm nhân viên:\n    + Nhập thông tin nhân viên\n    + Chọn \" Thêm mới\"\n    + Nhập và xác nhận mật khẩu\n    + Chọn \"Xác nhận\" \n - Cập nhật thông tin nhân viên:\n    + Click đúp nhân viên muốn cập nhật thông tin trong bảng danh sách nhân viên\n    + Cập nhật thông tin nhân viên\n    + Chọn \"Cập nhật\"\n - Tìm kiếm nhân viên:\n    + Chọn thông tin hoặc nhập từ khóa mã hoặc tên nhân viên cần tìm\n    + Chọn \"Tìm kiếm\"\nThanh toán:\n - Thanh toán đơn hàng:\n    + Chọn sản phẩm và số lượng \n    + Chọn \"Thêm vào đơn hàng\"\n    + Chọn phương thức thanh toán\n    + Chọn \"Thanh toán\"\n - Tạo đơn giao hàng:\n    + Chọn sản phẩm và số lượng \n    + Chọn \"Thêm vào đơn hàng\"\n    + Chọn phương thức thanh toán\n    + Chọn \"Giao hàng\"\n - Tìm kiếm hóa đơn:\n    + Nhập mã hóa đơn\n    + Chọn \"Tìm kiếm\"\n - Đổi hàng:\n    + Chọn hóa đơn yêu cầu đổi hàng\n    + Chọn sản phẩm khách muốn đổi\n    + Chọn \"Yêu cầu đổi trả\"\n    + Chọn sản phẩm khách muốn nhận\n    + Chọn \"Đổi hàng\"\nQuản lý tài khoản:\n - Cập nhật thông tin tài khoản:\n    + Chọn \"Hệ thống\" trong thanh Menu\n    + Chọn \"Thông tin tài khoản\"\n    + Cập nhật lại thông tin\n    + Chọn \"Update\"\n - Đổi mật khẩu:\n    + Chọn \"Hệ thống\" trong thanh Menu\n    + Chọn \"Đổi mật khẩu\"\n    + Xác nhận mật khẩu cũ và nhập mật khẩu mới\n    + Chọn \"Confirm\"");
        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
